In [2]:
import numpy
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [6]:
print(n.reshape(3, 9))
print("\n")
print(n.reshape(3, 3, 3))

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [9]:
m = numpy.asarray([[123, 12, 123, 12, 33], [], []])
m

array([list([123, 12, 123, 12, 33]), list([]), list([])], dtype=object)

In [10]:
import cv2

In [19]:
im_g = cv2.imread("smallgray.png", 0)   # read png as 0 grayscale, 1 as BGR
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [18]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [20]:
# indexing numpy, similar as indexing list
im_g[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [22]:
# iterating a numpy array
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [24]:
# print the elements in im_g one by one
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [28]:
# hstack means stacking the arrays horizontally
ims_h = numpy.hstack((im_g, im_g))
print(ims_h)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [29]:
# vstack means stacking the arrays vertically
ims_v = numpy.vstack((im_g, im_g))
print(ims_v)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [45]:
# split
lst = numpy.hsplit(ims_h, 2)
print(lst)

print("\n")

lst = numpy.vsplit(ims_h, 3)
print(lst)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]


[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8), array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147]], dtype=uint8), array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)]
